# Generated by Django 5.1.3 on 2024-12-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Districtaveragescores',
        ),
        migrations.RemoveField(
            model_name='districttoschool',
            name='districtid',
        ),
        migrations.RemoveField(
            model_name='dropoutrates',
            name='aunyear',
        ),
        migrations.DeleteModel(
            name='Districtperformance',
        ),
        migrations.DeleteModel(
            name='Lowincomeschoolsdesignatedforteacherloan',
        ),
        migrations.RemoveField(
            model_name='percentlowincomebyschool',
            name='schoolnumber',
        ),
        migrations.DeleteModel(
            name='Publicdropoutrates',
        ),
        migrations.DeleteModel(
            name='Schoolperformancee',
        ),
        migrations.DeleteModel(
            name='Schoolperformanceehup',
        ),
        migrations.DeleteModel(
            name='Schoolperformanceeupf',
        ),
        migrations.DeleteModel(
            name='Schoolperformancem',
        ),
        migrations.DeleteModel(
            name='Schoolperformancemhup',
        ),
        migrations.DeleteModel(
            name='Schoolperformancemupf',
        ),
        migrations.DeleteModel(
            name='Schoolperformances',
        ),
        migrations.DeleteModel(
            name='Schoolperformanceshup',
        ),
        migrations.DeleteModel(
            name='Schoolperformancesupf',
        ),
        migrations.AlterModelTable(
            name='schooldata',
            table='test_data',
        ),
        migrations.DeleteModel(
            name='Districtdata',
        ),
        migrations.DeleteModel(
            name='Districttoschool',
        ),
        migrations.DeleteModel(
            name='Districtidtoyear',
        ),
        migrations.DeleteModel(
            name='Dropoutrates',
        ),
        migrations.DeleteModel(
            name='Percentlowincomebyschool',
        ),
    ]
