# Generated by Django 5.2.dev20240911160443 on 2024-10-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('district_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('aun', models.IntegerField()),
                ('schl', models.IntegerField(primary_key=True, serialize=False)),
                ('school_address_street', models.CharField(max_length=255)),
                ('school_address_city', models.CharField(max_length=255)),
                ('school_zip_code', models.CharField(max_length=10)),
                ('school_enrollment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_gifted_student', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
